### ISSUE TITLE
Add a way to be sure of the order on how the application will be imported/run

### ISSUE THREAD

**Issue by dupbr01** [ActianCorp/OpenROAD_UnitTestFramework#10]
We need to define a rule so that when a testcase requires to have other included application(s) part of the test we are are sure we include first the included application(s), that maybe even do not need to be run.
I guess if the included application(s) do not need to be run we are OK we can just put empty test. But for the main application we need to be sure the included applications have been already imported.

**Comment by clach04** [comment]
@dupbr01 Potential lightweight option, something that is easy to understand and quick to implement would be filename (alpha-numeric) sort order. E.g.

  * TestSomething_0_Main
  * TestSomething_1_IncludesMainAbove

We'd just add a sort to the `ls` already used on import and update readme with it as a convention. issues #7 would be a pre-requisite or the convention would be to no put test methods in the include component(s).
